### ISSUE TITLE
py errors

### ISSUE THREAD

**Issue by smika** [flickerfly/taskwarrior-notifications#4]
Hi I tried this script. Does this script still working? Or is this too old for the recent software?

When I run task email, i got the following errors:

vis@servername:~/scripts$ ./task-email.sh
Traceback (most recent call last):
  File "/home/vis/scripts/taskwarrior-notifications/scripts/export-html.py", line 33, in <module>
    main()
  File "/home/vis/scripts/taskwarrior-notifications/scripts/export-html.py", line 23, in main
    lin = eval(line)
  File "<string>", line 1
    [
    ^
SyntaxError: unexpected EOF while parsing
Traceback (most recent call last):
  File "/home/vis/scripts/taskwarrior-notifications/scripts/export-html.py", line 33, in <module>
    main()
  File "/home/vis/scripts/taskwarrior-notifications/scripts/export-html.py", line 23, in main
    lin = eval(line)
  File "<string>", line 1
    [
    ^
SyntaxError: unexpected EOF while parsing
Traceback (most recent call last):
  File "/home/vis/scripts/taskwarrior-notifications/scripts/export-html.py", line 33, in <module>
    main()
  File "/home/vis/scripts/taskwarrior-notifications/scripts/export-html.py", line 23, in main
    lin = eval(line)
  File "<string>", line 1
    [
    ^
SyntaxError: unexpected EOF while parsing
Traceback (most recent call last):
  File "/home/vis/scripts/taskwarrior-notifications/scripts/export-html.py", line 33, in <module>
    main()
  File "/home/vis/scripts/taskwarrior-notifications/scripts/export-html.py", line 23, in main
    lin = eval(line)
  File "<string>", line 1
    [
    ^
SyntaxError: unexpected EOF while parsing

Thanks in advanced,

Smika

**Comment by flickerfly** [comment]
I haven't used it myself in awhile. I've only just gotten back to using taskwarrior due to a job change. It is entirely possible that there are some problems with it.
